TABLE - 1 AREACITY "DONE"


CREATE TABLE AREACITY(
AREAID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
AREA VARCHAR2(100),
CITY VARCHAR2(100),
CONSTRAINT AREACITY_PK PRIMARY KEY (AREAID));


/*********************************************************************************************/

TABLE - 2 AUTOMOBILEMAKEMODEL "DONE"

CREATE TABLE AUTOMOBILEMAKEMODEL(
AUTOMOBILEMAKEMODELID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
AUTOMOBILEMODELYEAR VARCHAR2(4),
MAKE VARCHAR2(100),
MODEL VARCHAR2(100),
CONSTRAINT AUTOMOBILEMAKEMODEL_PK PRIMARY KEY (AUTOMOBILEMAKEMODELID ));


/*********************************************************************************************/

TABLE - 3 SERVICECENTER "DONE"

CREATE TABLE SERVICECENTER(
SERVICECENTERID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
AREAID NUMBER(*,0),
SERVICECENTERNAME VARCHAR2(100),
SERVICECENTERTELEPHONENUMBER VARCHAR2(100),
SERVICECENTERMOBILENUMBER VARCHAR2(100),
SERVICECENTEREMAILADDRESS VARCHAR2(100),
ADDRESS VARCHAR2(500),
CONSTRAINT SERVICECENTER_ID PRIMARY KEY (SERVICECENTERID),
CONSTRAINT SERVICECENTERAREA_FK FOREIGN KEY (AREAID) REFERENCES AREACITY (AREAID)); 

/***********************************************************************************************/



TABLE - 4 DEPARTMENTS  "DONE"


CREATE TABLE DEPARTMENTS(
DNO NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
DNAME VARCHAR2(100),
AREAID NUMBER(*,0),
SERVICECENTERID NUMBER(*,0),
CONSTRAINT DEPARTMENTID_PK PRIMARY KEY (DNO),
CONSTRAINT DEPARTMENTINSERVICECENTER_FK FOREIGN KEY (SERVICECENTERID) REFERENCES SERVICECENTER (SERVICECENTERID),
CONSTRAINT DEPARTMENTINAREACITY_FK FOREIGN KEY (AREAID) REFERENCES AREACITY (AREAID));


/*********************************************************************************************/


/*
CREATE TABLE MGROFDEPT(
MGRDEPTID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
MGRID NUMBER(*,0),
DNO NUMBER(*,0),
CONSTRAINT MGROFDEPARTMENT_FK FOREIGN KEY (MGRID) REFERENCES EMPLOYEES (EMPID),
CONSTRAINT DEPARTMENTOFMGR_FK FOREIGN KEY (DNO) REFERENCES DEPARTMENTS (DNO),
CONSTRAINT MGROFDEPT_PK PRIMARY KEY (MGRDEPTID));


*/













/**************************************************************************************************/


TABLE - 5 JOBS "OK"

CREATE TABLE JOBS(
JOBID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY
DNO NUMBER(*,0),
EMPJOB VARCHAR2(100),
AREAID NUMBER(*,0),
SERVICECENTERID NUMBER(*,0),
CONSTRAINT JOB_PK PRIMARY KEY (JOBID),
CONSTRAINT JOBINAREACITY_FK FOREIGN KEY (AREAID) REFERENCES AREACITY (AREAID),
CONSTRAINT JOBINSERVICECENTER_FK FOREIGN KEY (SERVICECENTERID) REFERENCES SERVICECENTER (SERVICECENTERID)
);


/***************************************************************************************************/












TABLE - 6 EMPLOYEES        "OK"


CREATE TABLE EMPLOYEES(
EMPID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
DNO NUMBER(*,0),
JOBID NUMBER(*,0),
SERVICECENTERID NUMBER(*,0),
EMPNAME VARCHAR2(100),
EMPSALARY NUMBER(*,0),
MOBILENUMBER VARCHAR2(100),
HIREDATE DATE,
ADDRESS VARCHAR2(500),
EMPEMAILADDRESS VARCHAR2(100),
TELEPHONENUMBER VARCHAR2(100),
EMPUSERNAME VARCHAR2(100),
EMPPASSWORD VARCHAR2(64),
CONSTRAINT EMPID_PK PRIMARY KEY (EMPID),
CONSTRAINT EMPINSERVICECENTER_FK FOREIGN KEY (SERVICECENTERID) REFERENCES SERVICECENTER (SERVICECENTERID),
CONSTRAINT EMPINDEPARTMENT_FK FOREIGN KEY (DNO) REFERENCES DEPARTMENTS (DNO),
CONSTRAINT EMPJOB_FK FOREIGN KEY (JOBID) REFERENCES JOBS (JOBID)

); 

/***********************************************************************************************************************/



--ALTER TABLE DEPARTMENTS ADD CONSTRAINT MGROFDEPARTMENT_FK FOREIGN KEY (MGRID) REFERENCES EMPLOYEES (EMPID);



ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPINDEPARTMENT_FK FOREIGN KEY (DNO) REFERENCES DEPARTMENTS (DNO);

ALTER TABLE EMPLOYEES ADD CONSTRAINT EMPJOB_FK FOREIGN KEY (JOBID) REFERENCES JOBS (JOBID);








/*

TABLE - 6 DEPARTMENTOFJOB    "OK"

CREATE TABLE DEPARTMENTOFJOB(
DEPARTMENTOFJOBID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,	
JOBID NUMBER(*,0),
DNO NUMBER(*,0),
CONSTRAINT DEPARTMENTOFJOB_FK FOREIGN KEY (DNO) REFERENCES DEPARTMENTS (DNO),
CONSTRAINT JOBINWHICHDEPARTMENT_FK FOREIGN KEY (JOBID) REFERENCES JOBS (JOBID),
CONSTRAINT JOBDEPT_PK PRIMARY KEY (JOBID,DNO));

Table - 8 MGROFDEPT  "OK"

CREATE TABLE MGROFDEPT(
MGRDEPTID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
MGRID NUMBER(*,0),
DNO NUMBER(*,0),
CONSTRAINT MGROFDEPARTMENT_FK FOREIGN KEY (MGRID) REFERENCES EMPLOYEES (EMPID),
CONSTRAINT DEPARTMENTOFMGR_FK FOREIGN KEY (DNO) REFERENCES DEPARTMENTS (DNO),
CONSTRAINT MGROFDEPT_PK PRIMARY KEY (MGRDEPTID));

**********************************************************************************************
Table - 9 JOBOFEMPLOYEE  "OK"

CREATE TABLE JOBOFEMPLOYEE(
JOBOFEMPLOYEE NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
EMPID NUMBER(*,0),
JOBID NUMBER(*,0),
CONSTRAINT EMPJOB_FK FOREIGN KEY (JOBID) REFERENCES JOBS (JOBID),
CONSTRAINT EMPID_FK FOREIGN KEY (EMPID) REFERENCES EMPLOYEES (EMPID)




);

**********************************************************************************************

Table - 10 DEPARTMENTOFEMPLOYEE     "OK"

CREATE TABLE DEPARTMENTOFEMPLOYEE(
DEPARTMENTOFEMPLOYEE NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
DNO NUMBER(*,0),
EMPID NUMBER(*,0),
CONSTRAINT DEPOFEMP_FK FOREIGN KEY (DNO) REFERENCES DEPARTMENTS (DNO),
CONSTRAINT EMPIDDEP_FK FOREIGN KEY (EMPID) REFERENCES EMPLOYEES (EMPID)
);



**********************************************************************************************



*/


TABLE - 7 CUSTOMERS         "OK"


CREATE TABLE CUSTOMERS(
CUSTOMERID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
SERVICECENTERID NUMBER(*,0),
CUSTOMERNAME VARCHAR2(100),
CUSTOMEREMAILADDRESS VARCHAR2(100),
MOBILENUMBER VARCHAR2(100),
ADDRESS VARCHAR2(500),
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMERID),
CONSTRAINT CUSTOMERINSERVICECENTER_FK FOREIGN KEY (SERVICECENTERID) REFERENCES SERVICECENTER (SERVICECENTERID));


/**********************************************************************************************/

TABLE - 8 AUTOMOBILES             "OK" 
CREATE TABLE AUTOMOBILES(
AUTOMOBILEID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
CUSTOMERID NUMBER(*,0),
NUMBERPLATE VARCHAR2(50),
AUTOMOBILEMAKEMODELID NUMBER(*,0),
CHASSISNUMBER VARCHAR2(50),
MILEAGE DOUBLE PRECISION,
CONSTRAINT AUTOMOBILE_PK PRIMARY KEY (AUTOMOBILEID),
CONSTRAINT AUTOMOBILEMAKEMODEL_FK FOREIGN KEY (AUTOMOBILEMAKEMODELID) REFERENCES AUTOMOBILEMAKEMODEL (AUTOMOBILEMAKEMODELID),
CONSTRAINT CUSTOMERIDOWNERAUTOMOBILE_FK FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS (CUSTOMERID)
);

/**********************************************************************************************/

/*
TABLE - 13 AUTOMOBILEOFWHICHCUSTOMER    "OK"

CREATE TABLE AUTOMOBILEOFWHICHCUSTOMER(
AUTOMOBILEOFWHICHCUSTOMER NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
AUTOMOBILEID NUMBER(*,0),
CUSTOMERID NUMBER(*,0),
CONSTRAINT AUTOMOBILEOFWHICHCUSTOMER_FK FOREIGN KEY (AUTOMOBILEID) REFERENCES AUTOMOBILES (AUTOMOBILEID),
CONSTRAINT CUSTOMERIDOWNERAUTOMOBILE_FK FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS (CUSTOMERID),
);



**********************************************************************************************
*/

/*
TABLE - 14 PARTINFO     "OK"


CREATE TABLE PARTINFO(
PARTINFOID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
PARTTYPE VARCHAR2(100),
PARTSIZE VARCHAR(100),
PARTQUANTITY VARCHAR2(100),
PARTVISCOSITY VARCHAR2(100),
PARTCOLOR VARCHAR2(100),
PARTDESCRIPTION VARCHAR2(100),
CONSTRAINT PARTINFOID_PK PRIMARY KEY (PARTINFOID)
);



**********************************************************************************************


*/


TABLE - 9 PARTS "OK"




CREATE TABLE PARTS
   (	 PARTID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
   PARTNUMBER VARCHAR2(500 BYTE) UNIQUE,
	AUTOMOBILEMAKEMODELID NUMBER(*,0), 
	SERVICECENTERID NUMBER(*,0), 
	PARTNAME VARCHAR2(300 BYTE), 
	UNITPRICE FLOAT(126), 
	QUANTITYINSTOCK NUMBER(*,0), 
	PARTTYPE VARCHAR2(100 BYTE), 
	PARTSIZE VARCHAR2(100 BYTE), 
	PARTQUANTITY VARCHAR2(100 BYTE), 
	PARTVISCOSITY VARCHAR2(100 BYTE), 
	PARTCOLOR VARCHAR2(100 BYTE), 
	PARTDESCRIPTION VARCHAR2(100 BYTE), 
	PARTBRAND VARCHAR2(100 BYTE), 
	PARTKW VARCHAR2(100 BYTE), 
	PARTHP VARCHAR2(100 BYTE), 
	PARTFUEL VARCHAR2(100 BYTE), 
	PARTCYLINDERS VARCHAR2(100 BYTE), 
	MANUFACTURESTART_YEAR VARCHAR2(100 BYTE), 
	MANUFACTUREEND_YEAR VARCHAR2(100 BYTE),
  CONSTRAINT PART_PK PRIMARY KEY (PARTID),
CONSTRAINT PARTINSERVICECENTER_FK FOREIGN KEY (SERVICECENTERID) REFERENCES SERVICECENTER (SERVICECENTERID));



/**********************************************************************************************/







TABLE - 10 SERVICEHISTORY     "OK"

CREATE TABLE SERVICEHISTORY(
SERVICEID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
SERVICECENTERID NUMBER(*,0),
CUSTOMERID NUMBER(*,0),
AUTOMOBILEID NUMBER(*,0),
INVENTORYTOTAL DOUBLE PRECISION,
LABOURTOTAL DOUBLE PRECISION,
GRANDTOTAL DOUBLE PRECISION,
SERVICEDONEONDATE DATE,
MILEAGEONNEXTSERVICE DOUBLE PRECISION,
NEXTSERVICEDUEDATE DATE,
CONSTRAINT SERVICEID_PK PRIMARY KEY (SERVICEID),
CONSTRAINT SERVICEINSERVICECENTER_FK FOREIGN KEY (SERVICECENTERID) REFERENCES SERVICECENTER (SERVICECENTERID),
CONSTRAINT SERVICETOCUSTOMER_FK FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS (CUSTOMERID),
CONSTRAINT SERVICEOFAUTOMOBILE_FK FOREIGN KEY (AUTOMOBILEID) REFERENCES AUTOMOBILES(AUTOMOBILEID));
**********************************************************************************************

TABLE - 11 PARTSUSEDINSERVICE     "OK"
CREATE TABLE PARTSUSEDINSERVICE(
PUSEDID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
SERVICEID NUMBER(*,0),
PARTID NUMBER(*,0),
PARTQUANTITYUSED NUMBER(*,0),
PARTCHARGES NUMBER(*,0),
CONSTRAINT PARTSUSED_PK PRIMARY KEY (PUSEDID),
CONSTRAINT PARTUSEDPARTID_FK FOREIGN KEY (PARTID) REFERENCES PARTS (PARTID),
CONSTRAINT PARTUSEDSERVICEID_FK FOREIGN KEY (SERVICEID) REFERENCES SERVICEHISTORY (SERVICEID));

**********************************************************************************************




TABLE - 12 EMPLOYEELABOUR               "OK"

CREATE TABLE EMPLOYEELABOUR(
LID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
SERVICECENTERID NUMBER(*,0),
DESCRIPTION VARCHAR2(600),
CHARGES DOUBLE PRECISION,
CONSTRAINT EMPLOYEELABOURID_PK PRIMARY KEY (LID),
CONSTRAINT SERVICEINSCENTER_FK FOREIGN KEY (SERVICECENTERID) REFERENCES SERVICECENTER (SERVICECENTERID));



TABLE - 13 LABOURUSEDINSERVICE     "OK"

CREATE TABLE LABOURUSEDINSERVICE(
LUSEDID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
SERVICEID NUMBER(*,0),
LID NUMBER(*,0),
LABOURCHARGES NUMBER(*,0),
CONSTRAINT LABOURUSED_PK PRIMARY KEY (LUSEDID),
CONSTRAINT LABOURUSEDLID_FK FOREIGN KEY (LID) REFERENCES EMPLOYEELABOUR (LID),
CONSTRAINT LABOURUSEDINSERVICEID_FK FOREIGN KEY (SERVICEID) REFERENCES SERVICEHISTORY (SERVICEID));










**********************************************************************************************