CREATE TABLE AREACITY(
AREAID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
AREA VARCHAR2(100),
CITY VARCHAR2(100),
CONSTRAINT AREACITY_PK PRIMARY KEY (AREAID));







CREATE TABLE SHOP(
SHOPID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
AREAID NUMBER(*,0),
SHOPNAME VARCHAR2(100),
SHOPTELEPHONENUMBER VARCHAR2(100),
SHOPMOBILENUMBER VARCHAR2(100),
SHOPEMAILADDRESS VARCHAR2(100),
ADDRESS VARCHAR2(500),
CONSTRAINT SHOP_ID PRIMARY KEY (SHOPID),
CONSTRAINT SHOPAREA_FK FOREIGN KEY (AREAID) REFERENCES AREACITY (AREAID));



CREATE TABLE DEPARTMENTS(
DNO NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
DNAME VARCHAR2(100),
AREAID NUMBER(*,0),
SHOPID NUMBER(*,0),
CONSTRAINT DEPARTMENTID_PK PRIMARY KEY (DNO),
CONSTRAINT DEPARTMENTINSHOP_FK FOREIGN KEY (SHOPID) REFERENCES SHOP (SHOPID),
CONSTRAINT DEPARTMENTINAREACITY_FK FOREIGN KEY (AREAID) REFERENCES AREACITY (AREAID));



CREATE TABLE JOBS(
JOBID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
DNO NUMBER(*,0),
EMPJOB VARCHAR2(100),
AREAID NUMBER(*,0),
SHOPID NUMBER(*,0),
CONSTRAINT JOB_PK PRIMARY KEY (JOBID),
CONSTRAINT JOBINAREACITY_FK FOREIGN KEY (AREAID) REFERENCES AREACITY (AREAID),
CONSTRAINT JOBINSHOP_FK FOREIGN KEY (SHOPID) REFERENCES SHOP (SHOPID)
);


CREATE TABLE EMPLOYEES(
EMPID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
DNO NUMBER(*,0),
JOBID NUMBER(*,0),
SHOPID NUMBER(*,0),
EMPNAME VARCHAR2(100),
EMPSALARY NUMBER(*,0),
MOBILENUMBER VARCHAR2(100),
HIREDATE DATE,
ADDRESS VARCHAR2(500),
EMPEMAILADDRESS VARCHAR2(100),
TELEPHONENUMBER VARCHAR2(100),
EMPUSERNAME VARCHAR2(100),
EMPPASSWORD VARCHAR2(64),
CONSTRAINT EMPID_PK PRIMARY KEY (EMPID),
CONSTRAINT EMPINSHOP_FK FOREIGN KEY (SHOPID) REFERENCES SHOP (SHOPID),
CONSTRAINT EMPINDEPARTMENT_FK FOREIGN KEY (DNO) REFERENCES DEPARTMENTS (DNO),
CONSTRAINT EMPJOB_FK FOREIGN KEY (JOBID) REFERENCES JOBS (JOBID)
); 


CREATE TABLE CUSTOMERS(
CUSTOMERID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
SHOPID NUMBER(*,0),
CUSTOMERNAME VARCHAR2(100),
CUSTOMEREMAILADDRESS VARCHAR2(100),
MOBILENUMBER VARCHAR2(100),
ADDRESS VARCHAR2(500),
CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMERID),
CONSTRAINT CUSTOMERINSHOP_FK FOREIGN KEY (SHOPID) REFERENCES SHOP (SHOPID));



CREATE TABLE CATEGORIES(
CATEGORYID  NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
CATEGORY VARCHAR2(500),
CONSTRAINT CATEGORYID_PK PRIMARY KEY (CATEGORYID)

)

CREATE TABLE SUBCATEGORIES(
SUBCATEGORYID  NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
CATEGORYID NUMBER(*,0),
SUBCATEGORY VARCHAR2(500),
CONSTRAINT SUBCATEGORYID_PK PRIMARY KEY (SUBCATEGORYID),
CONSTRAINT SUBCATEGORYOFCATEGORY_FK FOREIGN KEY (CATEGORYID) REFERENCES CATEGORIES (CATEGORYID));




CREATE TABLE MANUFACTURERS(
MANUFACTURERID  NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
MANUFACTURERNAME VARCHAR2(500),
MANUFACTUREREMAILADDRESS VARCHAR2(500),
MANUFACTURERTELEPHONENUMBER VARCHAR2(500),
MANUFACTURERADDRESS VARCHAR2(500),
MANUFACTURERMOBILENUMBER VARCHAR2(500),
CONSTRAINT MANUFACTURERID_PK PRIMARY KEY (MANUFACTURERID)
);


CREATE TABLE PRODUCTS
   (	 PRODUCTID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
	MANUFACTURERID NUMBER(*,0), 
	SHOPID NUMBER(*,0),
	CATEGORYID NUMBER(*,0),
	SUBCATEGORYID NUMBER(*,0),	
	PRODUCTNUMBER VARCHAR2(500),
	PRODUCTNAME VARCHAR2(300),
    PRODUCTDESCRIPTION VARCHAR2(4000), 	
	UNITPRICE NUMBER(*,0), 
	QUANTITYINSTOCK NUMBER(*,0), 
	PRODUCTSIZE VARCHAR2(100), 
	PRODUCTCOLOR VARCHAR2(100),
    PRODUCTWARRANTY VARCHAR2(100),
CONSTRAINT PRODUCTID_PK PRIMARY KEY (PRODUCTID),	
CONSTRAINT PRODUCTOFMANUFACTURER_FK FOREIGN KEY (MANUFACTURERID) REFERENCES MANUFACTURERS (MANUFACTURERID),	
CONSTRAINT PRODUCTINSHOP_FK FOREIGN KEY (SHOPID) REFERENCES SHOP (SHOPID),
CONSTRAINT PRODUCTCATEGORY_FK FOREIGN KEY (CATEGORYID) REFERENCES CATEGORIES (CATEGORYID),
CONSTRAINT PRODUCTSUBCATEGORY_FK FOREIGN KEY (SUBCATEGORYID) REFERENCES SUBCATEGORIES (SUBCATEGORYID));



CREATE TABLE BILL(
BILLID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
SHOPID NUMBER(*,0),
CUSTOMERID NUMBER(*,0),
BILLAMOUNT NUMBER(*,0),
BILLDATE varchar2(500),
CONSTRAINT BILLID_PK PRIMARY KEY (BILLID),
CONSTRAINT BILLINWHICHSHOP_FK FOREIGN KEY (SHOPID) REFERENCES SHOP (SHOPID),
CONSTRAINT BILLOFWHICHCUSTOMER_FK FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS (CUSTOMERID));




CREATE TABLE PRODUCTSBOUGHT(
PRODUCTBOUGHTID NUMBER(*,0) GENERATED ALWAYS AS IDENTITY,
BILLID NUMBER(*,0),
PRODUCTID NUMBER(*,0),
PRODUCTBOUGHTQUANTITY NUMBER(*,0),
PRODUCTCHARGES NUMBER(*,0),
CONSTRAINT PRODUCTBOUGHTID_PK PRIMARY KEY (PRODUCTBOUGHTID),
CONSTRAINT PRODUCTBOUGHTBILL_FK FOREIGN KEY (BILLID) REFERENCES BILL (BILLID),
CONSTRAINT PRODUCTBOUGHTID_FK FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS (PRODUCTID));






























